[package]
name = "kfsm"
version = "0.1.0"
authors = ["Giorgos Ntemiris <ntemirisgiorgos3@gmail.com>"]
description = "state machine"
license = "MIT"
repository = "https://github.com/gntem/kfsm"
edition = "2018"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
